### ISSUE TITLE
child config "request_password_repository" under "symfonycasts_reset_password" must be configured

### ISSUE THREAD

**Issue by ganti** [SymfonyCasts/reset-password-bundle#243] opened 2022-09-16 22:23 UTC
When changing `Kernel.php` to [inject other configs](https://tomasvotruba.com/blog/how-to-create-symfony-kernel-for-tests-with-different-configs/#4-Kernel-with-Configurable-Configs) the following error occurs:
```
The child config "request_password_repository" under "symfonycasts_reset_password" must be configured:
A class that implements ResetPasswordRequestRepositoryInterface - usually your ResetPasswordRequestRepository.
```

It fails here: 
[`vendor/symfonycasts/reset-password-bundle/src/DependencyInjection/SymfonyCastsResetPasswordExtension.php:31`](https://github.com/SymfonyCasts/reset-password-bundle/blob/0c524ef609899cb6cdccec662f19780fbb404167/src/DependencyInjection/SymfonyCastsResetPasswordExtension.php#L31)

When not using `reset-password-bundle` it works. Any idea on how to have `reset-password-bundle` with extra kernel configs together? 

---- 

Kernel.php
```php
<?php

namespace App;

use Symfony\Component\Config\Loader\LoaderInterface;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;
use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;


class Kernel extends BaseKernel
{
    use MicroKernelTrait;
    private $extraConfigs = [];

    public function __construct(string $environment, bool $debug, array $extraConfigs = [])
    {
        parent::__construct($environment, $debug);
        $this->extraConfigs = $extraConfigs;
    }

    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        foreach ($this->extraConfigs as $extraConfig) {
            $loader->load($extraConfig);
        }
    }
}
```

**Comment by weaverryan** [comment] 2022-09-19 13:09
Hi there!

I'm not really sure what the problem is. BUT, I do know that if ResetPasswordBundle is enabled in your bundle (which it is), then you MUST pass the `request_password_repository` key to the `symfonycasts_reset_password` config. My guess is that, based on whatever config you're passing to your kernel, you are passing NO `symfonycasts_reset_password` config. And so, you get this error. Put simply: this bundle is missing some config it needs to work :).

Closing, as I don't think there's a bug here - you just need to figure out why this config is missing.

Cheers!

**Closed by weaverryan** 2022-09-19 13:09 UTC
