### ISSUE TITLE
Password reset fails on non confirmed accounts

### ISSUE THREAD

**Issue by sjobke** [SymfonyCasts/reset-password-bundle#132] opened 2020-11-24 19:52 UTC
When people register and fail to confirm their account, password reset also fails.
Any ideas on how to fix this issue?

**Comment by weaverryan** [comment] 2020-11-25 14:26
Hey @sjobke!

Hmm. Can you tell us a bit more? I would think these would be independent of each other, but I could be wrong (that happens a lot ;) ). What behavior are you seeing?

Cheers!

**Comment by sjobke** [comment] 2020-11-26 10:12
Imagine this journey. You create an account, you fail to receive the confirmation e-mail. Then you try to restore your password, but that does not work for unconfirmed accounts. Registering again  is not possible as email is already in use.

**Comment by jrushlow** [comment] 2020-11-27 15:58
Are you using the `syfomycasts/verify-email-bundle` for email verifications?

In general, reset password doesn't care if an account if verified or not. However, it is possible code else is preventing verification from happening.

**Comment by jrushlow** [comment] 2020-12-18 14:27
@sjobke I'm going to close this issue for now as I don't believe the cause is directly related to `ResetPasswordBundle`. Feel free to reopen if you're still reexperience issues. Thanks!

**Closed by jrushlow** 2020-12-18 14:27 UTC
Labels: unconfirmed
